{
  inputs = {
    chaotic = {
      url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
    };
    home-manager = {
      follows = "chaotic/home-manager";
    };
    icedos-github_icedos_apps = {
      url = "github:icedos/apps/d3e141f629bcc0e442f74faa0eb8801231728855";
    };
    icedos-github_icedos_apps-aagl-aagl = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:ezKEa/aagl-gtk-on-nix";
    };
    icedos-github_icedos_apps-celluloid-celluloid-shader = {
      flake = false;
      url = "path:///nix/store/5zcj323fgw0vxx0nhgvp45yxrwikm0c6-FSR.glsl";
    };
    icedos-github_icedos_desktop = {
      url = "github:icedos/desktop/fb1b25d21e254d2ee56e116dfebe7ac7759e6235";
    };
    icedos-github_icedos_gnome = {
      url = "github:icedos/gnome/884a9f13516c18db04ce26898a7a17434b792e01";
    };
    icedos-github_icedos_hardware = {
      url = "github:icedos/hardware/67ac42ddaff456bb1f422cf76d203d7bb64a1e23";
    };
    icedos-github_icedos_providers = {
      url = "github:icedos/providers/c8c06c007923371a6baedcabe55cb1b209f0f04b";
    };
    icedos-github_icedos_tweaks = {
      url = "github:icedos/tweaks/83d42744d78c418a259b8e1c4ae7eba1d3e9eaf5";
    };
    icedos-github_icedos_users = {
      url = "github:icedos/users/9ddc3663045cd05e7df3d99844b4b640741fe667";
    };
    nixpkgs = {
      follows = "chaotic/nixpkgs";
    };
  };

  outputs =
    {
      home-manager,
      nixpkgs,
      self,
      ...
    }@inputs:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      inherit (pkgs) lib;
      inherit (lib) fileContents map;

      inherit (builtins) fromTOML;
      inherit ((fromTOML (fileContents ./config.toml))) icedos;

      icedosLib = import ./lib {
        inherit lib pkgs inputs;
        config = icedos;
        self = ./.;
      };

      inherit (icedosLib) modulesFromConfig;
    in
    {
      nixosConfigurations."nixos" = nixpkgs.lib.nixosSystem rec {
        specialArgs = {
          inherit icedosLib inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/orfous/dev/OrfOsCore";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.systemBuilderCommands = "ln -s ${self} $out/source";
          }

          # Internal modules and config
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                map (dir: "/${path}/${dir}") (
                  let
                    inherit (lib) attrNames;
                  in
                  attrNames (filterAttrs (n: v: v == "directory") (builtins.readDir path))
                );
            in
            {
              imports = [ ./modules/options.nix ] ++ getModules ./.extra ++ getModules ./.private;
              config.system.stateVersion = "23.05";
            }
          )

          home-manager.nixosModules.home-manager

          { icedos.system.isFirstBuild = false; }

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "nvme"
                "xhci_pci"
                "ahci"
                "usbhid"
                "usb_storage"
                "sd_mod"
              ];
              boot.initrd.kernelModules = [ ];
              boot.kernelModules = [ "kvm-amd" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/2d2507f5-9d13-4580-9b63-7847206f17bb";
                fsType = "btrfs";
                options = [ "subvol=@" ];
              };

              boot.initrd.luks.devices."luks-12fedaa1-486a-4da2-acda-6f3b6c7d1d64".device =
                "/dev/disk/by-uuid/12fedaa1-486a-4da2-acda-6f3b6c7d1d64";

              fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/0025-0666";
                fsType = "vfat";
              };

              swapDevices = [ ];

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

          ({ })

        ]
        ++ modulesFromConfig.options
        ++ (modulesFromConfig.nixosModules { inherit inputs; });
      };
    };
}
